services:
  - type: web
    name: experimental-bell-bot
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
